version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "4000:27017"

  nodejs:
    image: yashcse21/major1:node_app
    container_name: nodejs
    environment:
      - DB=mongodb://mongodb:27017
      - SECRET=mysecretisthis
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - knn
  knn:
    image: yashcse21/major1:knn
    container_name: knn
    ports:
      - "3000:3000"
